language: node_js
node_js:
- "node"
script:
  - npm run storybook:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: ./packages/designSystem/storybook-static
  on:
    branch: master